# Generated by Django 5.1.3 on 2024-12-01 14:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='read',
            name='img2',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='read',
            name='img3',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
